baseURL = "https://afr-dt.github.io/"
defaultContentLanguage = "es"
enableEmoji = true

[module]
[[module.imports]]
path = "github.com/luizdepra/hugo-coder"

[pagination]
pagerSize = 6

[markup]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[params]
author = "Alejandro Flores"
keywords = "blog,developer,devops,backend,python,gcp"
colorScheme = "auto"
since = 2019

[languages]
  [languages.es]
    label = "Español"
    locale = "es"
    weight = 1
    title = "Alejandro Flores"
    [languages.es.params]
      info = ["Ingeniero Backend & DevOps"]
      description = "Blog personal de Alejandro Flores"
    [[languages.es.menu.main]]
      name = "Sobre mí"
      weight = 1
      url = "about/"
    [[languages.es.menu.main]]
      name = "Blog"
      weight = 2
      url = "posts/"

  [languages.en]
    label = "English"
    locale = "en"
    weight = 2
    title = "Alejandro Flores"
    [languages.en.params]
      info = ["Backend & DevOps Engineer"]
      description = "Alejandro Flores' personal blog"
    [[languages.en.menu.main]]
      name = "About"
      weight = 1
      url = "about/"
    [[languages.en.menu.main]]
      name = "Blog"
      weight = 2
      url = "posts/"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/afr-dt"
target = "_blank"
rel = "noopener noreferrer"

[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/afr-dt"
target = "_blank"
rel = "noopener noreferrer"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 3
url = "https://linkedin.com/in/afr-dt"
target = "_blank"
rel = "noopener noreferrer"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 4
url = "https://twitter.com/afr_dt"
target = "_blank"
rel = "noopener noreferrer"

[[params.social]]
name = "Email"
icon = "fa-solid fa-envelope fa-2x"
weight = 5
url = "mailto:aleksgnu@gmail.com"
